android: [NFC] Refactor TableGen for attributes
Changes due to commit cfe87a4a16b ("[NFC] Refactor TableGen for attributes")

Fixes the following buiding error:

error: external/llvm-project/llvm/lib/IR/Android.bp:10:1: module "llvm-gen-core":
module source path "external/llvm-project/llvm/lib/IR/AttributesCompatFunc.td" does not exist

make: *** No rule to make target 'external/llvm11/lib/IR/AttributesCompatFunc.td', needed by '/1/1/out/target/product/android_x86/gen/STATIC_LIBRARIES/libLLVM11Core_intermediates/AttributesCompatFunc.inc'.  Stop.

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>