android: Fix out-of-tree clang build due to sysexits change
Porting of commit
5e4409f ("Fix out-of-tree clang build due to sysexits change")

Fixes the following building errors:

In file included from external/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:12:
external/llvm-project/llvm/include/llvm/Support/ExitCodes.h:30:2: error: Exit code EX_IOERR not available
 ^
external/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:385:15: error: use of undeclared identifier 'EX_IOERR'
    RetCode = EX_IOERR;
              ^
2 errors generated.