Revert "[ADT] Make Optional a literal type."
This reverts commit 94948f3c929e221214ba8acf419b1cddb61e042e.

external/llvm12/include/llvm/ADT/Optional.h:113:43: error: call to implicitly-deleted copy constructor of 'llvm::CFLSteensAAResult::FunctionInfo'
    ::new ((void *)std::addressof(value)) T(std::forward<Args>(args)...);
                                          ^ ~~~~~~~~~~~~~~~~~~~~~~~~
external/llvm12/include/llvm/ADT/Optional.h:74:7: note: in instantiation of function template specialization 'llvm::optional_detail::OptionalStorage<llvm::CFLSteensAAResult::FunctionInfo, false>::emplace<const llvm::CFLSteensAAResult::FunctionInfo &>' requested here
      emplace(other.value);
      ^
external/llvm12/lib/Analysis/CFLSteensAliasAnalysis.cpp:73:37: note: copy constructor of 'FunctionInfo' is implicitly deleted because field 'Sets' has a deleted copy constructor
  StratifiedSets<InstantiatedValue> Sets;
                                    ^
external/llvm12/lib/Analysis/StratifiedSets.h:87:3: note: copy constructor is implicitly deleted because 'StratifiedSets<llvm::cflaa::InstantiatedValue>' has a user-declared move constructor
  StratifiedSets(StratifiedSets &&) = default;
  ^
1 error generated.
make: *** [build/core/binary.mk:986: /1/1/out/target/product/android_x86/obj/STATIC_LIBRARIES/libLLVM12Analysis_intermediates/CFLSteensAliasAnalysis.o] Error 1