android: Rename {Attributes,Intrinsics}.gen to {Attributes,Intrinsics}.inc
Fix the following building errors:

In file included from external/llvm/lib/Linker/LinkModules.cpp:21:
In file included from external/llvm/include/llvm/IR/Module.h:23:
external/llvm/include/llvm/IR/Attributes.h:74:14: fatal error: 'llvm/IR/Attributes.inc' file not found
    #include "llvm/IR/Attributes.inc"
             ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
...
In file included from external/llvm/lib/Linker/IRMover.cpp:19:
external/llvm/include/llvm/IR/Intrinsics.h:42:10: fatal error: 'llvm/IR/Intrinsics.inc' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Reference:
ea0775ec4a ("Rename Attributes.gen, Intrinsics.gen to Attributes.inc, Intrinsics.inc")